"use client"

import { useEffect, useState } from "react"

export default function FormsPage() {
  const [fields, setFields] = useState<string[]>([])

  useEffect(() => {
    fetch("/api/system-config")
      .then((res) => res.json())
      .then((config) => {
        if (config?.suggestedIntakeFields) {
          setFields(config.suggestedIntakeFields)
        }
      })
  }, [])

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">
        Intake Form Configuration
      </h1>

      <div className="bg-white p-6 rounded-lg shadow">
        {fields.length === 0 ? (
          <p className="text-gray-600">
            No intake form configured yet.
            Run AI onboarding to generate one.
          </p>
        ) : (
          <>
            <p className="mb-4 text-gray-600">
              These fields were generated by AI onboarding:
            </p>

            <ul className="list-disc ml-5 space-y-1">
              {fields.map((field, index) => (
                <li key={index}>{field}</li>
              ))}
            </ul>
          </>
        )}
      </div>
    </div>
  )
}
